jah2488/classroom

app/controllers/days_controller.rb

Found the magic active support method.

Use the campus TZ when creating a day

---

db/migrate/20150722195237_fix_day_start.rb
db/schema.rb
spec/factories/days.rb

We can't default to Time.now because.

Fix Day Start default

---

app/assets/javascripts/components/grade_submission_form.js.jsx
app/controllers/submissions_controller.rb
app/policies/submission_policy.rb
config/routes.rb
spec/controllers/submissions_controller_spec.rb
spec/policies/submission_policy_spec.rb

* I moved complete/unfinish into the resource
* This helps us get ready to expose a clean API
* I think Pundit makes our split routes defunct?

Submission mark routes are cleaner

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/views/staff/badges/new.html.erb
config/initializers/refile.rb
db/migrate/20150727201118_drop_refile_attachments.rb
db/schema.rb

Use s3 for refile. Drop the attachments table. Will need to re-upload all badge images.

Refile uses S3

---

app/controllers/cohorts_controller.rb
app/controllers/reports_controller.rb
app/models/instructor.rb
app/models/student.rb

I fear I may have overlooked this in a pull request or merge conflict or something, but a lot of the reports code is just gone. Clicking to add a new report was an error, and actually creating a new report is still an error, but this is a start.
I wondered if maybe the report logic had moved someplace else or I was otherwise mistaken as to what is going on? @kurtisnelson

Reports pages are broken?

---

app/controllers/registrations_controller.rb

Show msg about confirm after sign up

---

app/assets/javascripts/application.js
app/assets/javascripts/components/new_tag.js.jsx
app/controllers/staff/assignments_controller.rb
app/models/assignment_tag.rb
app/views/staff/assignments/new.html.erb
spec/controllers/staff/assignments_controller_spec.rb

Assignments now are properly being assigned tags.

Fixing issue where assignments were not handling errors gracefully.

---

Gemfile
Gemfile.lock
app/controllers/staff/cohorts_controller.rb
app/decorators/cohort_decorator.rb
app/models/campus.rb
app/models/cohort.rb
app/models/day.rb
app/views/staff/cohorts/create.slim
app/views/staff/cohorts/new.slim
app/views/staff/days/index.slim
db/migrate/20150813203040_rename_first_day_to_start_time.rb
db/schema.rb
db/seeds.rb
spec/factories/cohorts.rb
spec/factories/days.rb
spec/features/staff_cohorts_spec.rb
spec/features/staff_dashes_spec.rb
spec/models/assignment_spec.rb
spec/models/cohort_spec.rb

Timezones suck. Here I attempt to get them to suck less.

Heisen Tests

---

Dockerfile
config/database.yml
docker-compose.yml

Docker config

---

app/controllers/cohorts_controller.rb
app/models/cohort.rb
app/views/cohorts/_attendance.html.erb
app/views/cohorts/show.html.erb

This should remove the issue where students cannot view the app on days where there is no lecture. The one that was causing this issue.
```
An exception occurred: 'undefined method `decorate' for nil:NilClass' on '/app/app/controllers/cohorts_controller.rb:13:in `show''
*Backtrace:*
app/controllers/cohorts_controller.rb:13:in `show'
```

Don't look for current day if there is none.

---

app/assets/javascripts/components/time_field.js.jsx
app/helpers/application_helper.rb
app/views/staff/cohorts/_attendance.html.slim
app/views/students/show.html.slim

Adding assignments table to profile

---

app/models/submission.rb

Validate submission links

---

app/controllers/staff/assignments_controller.rb
app/views/staff/assignments/edit.html.erb

Now with 100% cleaner commit history and more functionality.

Fixing staff assignment edit.

---

app/controllers/staff/campuses_controller.rb
app/models/campus.rb
app/models/cohort.rb
app/views/layouts/application.html.slim
app/views/staff/campuses/index.slim
app/views/staff/campuses/new.slim
app/views/staff/cohorts/new.slim
config/initializers/inflections.rb
config/routes.rb
db/migrate/20150825161226_rename_campus.rb
db/migrate/20150825161912_rename_tz_on_campus.rb
db/schema.rb
spec/factories/campus.rb

Campuses can be created

---

app/controllers/students_controller.rb
app/policies/student_policy.rb
app/views/students/show.html.slim
config/routes.rb
spec/features/student_spec.rb

Instructors can become one of their students

---

app/controllers/staff/cohorts_controller.rb
app/decorators/cohort_decorator.rb
app/models/cohort.rb
app/models/cohort_instructor.rb
app/models/instructor.rb
app/views/staff/cohorts/index.slim
app/views/staff/cohorts/new.slim
app/views/staff/days/index.slim
db/migrate/20150910161017_create_cohort_instructors.rb
db/schema.rb
db/seeds.rb
spec/controllers/assignments_controller_spec.rb
spec/controllers/staff/assignments_controller_spec.rb
spec/controllers/students_controller_spec.rb
spec/controllers/submissions_controller_spec.rb
spec/factories/cohort_instructor.rb
spec/factories/cohorts.rb
spec/features/cohort_spec.rb
spec/features/staff/cohorts_spec.rb
spec/features/staff/dashes_spec.rb
spec/features/staff/days_spec.rb
spec/features/student_spec.rb
spec/models/instructor_spec.rb
spec/policies/report_policy_spec.rb
spec/policies/student_policy_spec.rb
spec/policies/submission_policy_spec.rb

No UI yet for adding an AI, it must be done in the console.

Assistant Instructors

---

app/controllers/staff/cohorts_controller.rb
app/decorators/report_decorator.rb
app/models/user.rb
app/policies/cohort_policy.rb
db/migrate/20150917194048_remove_instructor_from_cohorts.rb
db/schema.rb
db/seeds.rb
spec/features/staff/days_spec.rb
spec/features/staff/reports_spec.rb
spec/policies/cohort_policy_spec.rb
spec/policies/report_policy_spec.rb

Cleanup unused instructor column

---

app/views/staff/cohorts/_ungraded_assignments.slim

Adding ungraded count on ungraded assignments.

---

app/helpers/application_helper.rb
app/views/cohorts/_assignments.html.slim

Adding a legend to define what icons on the user dash mean.

---

app/helpers/application_helper.rb

Adding in correct definition of late and incomplete assignments.

---

app/controllers/assignments_controller.rb
app/controllers/staff/assignments_controller.rb
app/decorators/assignment_decorator.rb
app/models/assignment.rb
app/policies/assignment_policy.rb
app/views/assignments/show.html.slim
app/views/staff/assignments/_form.slim
app/views/staff/assignments/index.slim
app/views/staff/assignments/show.html.slim
db/migrate/20151018175742_add_start_to_assignments.rb
db/schema.rb

Assignment Start Time

---

app/assets/javascripts/components/cohort.js.jsx
app/assets/javascripts/components/cohort_lookup.js.jsx
app/assets/javascripts/components/student_enroll.js.jsx
app/assets/javascripts/components/user.js.jsx
app/assets/javascripts/components/user_lookup.js.jsx
app/controllers/cohorts_controller.rb
app/controllers/students_controller.rb
app/controllers/users_controller.rb
app/decorators/student_decorator.rb
app/models/cohort.rb
app/models/student.rb
app/models/user.rb
app/policies/student_policy.rb
app/views/application/_students.html.slim
app/views/staff/cohorts/show.slim
app/views/students/index.slim
app/views/students/new.slim
config/routes.rb
db/migrate/20150930211042_remove_dupe_phone.rb
db/schema.rb
spec/factories/students.rb
spec/factories/users.rb

Removes the materialize sheet because it was not playing well with normal bootstrap overrides.
I went through the whole app and cleaned up anything that was awkward, we can get the materialness back just by overriding .btn ourselves I think.

Instructor can enroll user

---

app/assets/javascripts/components/attendance.js.jsx
app/decorators/student_decorator.rb
app/models/cohort.rb
app/models/student.rb
app/views/cohorts/_attendance.html.slim
app/views/cohorts/_reports.slim
app/views/cohorts/show.slim
app/views/reports/show.pdf.erb
app/views/students/show.html.slim

Various Student Stats

---

app/controllers/staff/cohorts_controller.rb
app/decorators/operator_decorator.rb
app/helpers/application_helper.rb
app/models/campus.rb
app/models/cohort.rb
app/models/operator.rb
app/models/user.rb
app/policies/cohort_policy.rb
app/policies/report_policy.rb
app/policies/student_policy.rb
app/views/layouts/application.html.slim
app/views/staff/application/_nav.slim
app/views/staff/cohorts/_instructors.slim
app/views/staff/cohorts/_operations.slim
app/views/staff/cohorts/staff.slim
app/views/staff/days/index.slim
app/views/staff/reports/_form.html.slim
config/routes.rb
db/migrate/20151023205517_add_title_to_instructors.rb
db/migrate/20151023211342_create_operators.rb
db/migrate/20151023211706_create_campuses_operators.rb
db/schema.rb
db/seeds.rb
spec/factories/cohorts.rb
spec/factories/instructors.rb
spec/factories/operators.rb
spec/policies/student_policy_spec.rb

Make campus ops users first-class citizens. Right now they have to be manually provisioned.
Updated seeds to model the nashville campus including a cd@example.com login.
Definitely needs some poking around before merging, very well might be bad policies.

Campus Ops

---

app/assets/javascripts/components/assignment.js.jsx
app/assets/javascripts/components/my_assignments.js.jsx
app/controllers/assignments_controller.rb
app/models/submission.rb
app/policies/adjustment_policy.rb
app/serializers/assignment_serializer.rb
config/locales/en.yml
spec/factories/days.rb

Filter now works on safari!

---

app/assets/javascripts/components/adjustment_review.js.jsx
app/assets/javascripts/components/adjustments.js.jsx
app/controllers/adjustments_controller.rb
app/controllers/staff/cohorts_controller.rb
app/serializers/checkin_serializer.rb
app/serializers/day_serializer.rb
app/views/staff/cohorts/show.slim
db/seeds.rb

Better Adjustments

---

app/assets/javascripts/components/checkin.js.jsx
app/assets/javascripts/components/too_far.js.jsx
app/models/checkin.rb

Validate one checkin per person per day (per visit)
